// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubscribeUsers.Models;

namespace SubscribeUsers.Migrations
{
    [DbContext(typeof(ADProjContext))]
    [Migration("20190814031312_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubscribeUsers.Models.UserDetails", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("EmailAdress")
                        .IsUnique()
                        .HasName("UQ__UserDeta__A84E02841694A7CA");

                    b.ToTable("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
